class AppPaddingTokens {
  const AppPaddingTokens._();

  static const double paddingNone = 0.0;
  static const double paddingXs = 4.0;
  static const double paddingSm = 8.0;
  static const double paddingM = 12.0;
  static const double paddingMd = 16.0;
  static const double paddingMld = 20.0;
  static const double paddingLg = 24.0;
  static const double paddingXl = 32.0;
  static const double paddingXxl = 40.0;
  static const double paddingXxxl = 48.0;
  static const double paddingXxxxl = 56.0;
  static const double paddingXxxxxl = 64.0;
  static const double paddingXxxxxxl = 72.0;
  static const double paddingXxxxxxxl = 80.0;
  static const double paddingXxxxxxxxl = 88.0;
  static const double paddingXxxxxxxxxl = 96.0;
  static const double paddingXxxxxxxxxxl = 104.0;
  static const double paddingXxxxxxxxxxxl = 112.0;
  static const double paddingXxxxxxxxxxxxl = 120.0;
  static const double paddingXxxxxxxxxxxxxl = 128.0;
  static const double paddingXxxxxxxxxxxxxxl = 136.0;
  static const double paddingXxxxxxxxxxxxxxxl = 144.0;
  static const double paddingXxxxxxxxxxxxxxxxl = 152.0;
  static const double paddingXxxxxxxxxxxxxxxxxl = 160.0;
  static const double paddingXxxxxxxxxxxxxxxxxxl = 168.0;
  static const double paddingXxxxxxxxxxxxxxxxxxxl = 176.0;
  static const double paddingXxxxxxxxxxxxxxxxxxxxl = 184.0;
  static const double paddingXxxxxxxxxxxxxxxxxxxxxl = 192.0;
  static const double paddingXxxxxxxxxxxxxxxxxxxxxxl = 200.0;
  static const double paddingXxxxxxxxxxxxxxxxxxxxxxxl = 208.0;
  static const double paddingXxxxxxxxxxxxxxxxxxxxxxxxl = 216.0;
  static const double paddingXxxxxxxxxxxxxxxxxxxxxxxxxl = 224.0;
  static const double paddingXxxxxxxxxxxxxxxxxxxxxxxxxxl = 232.0;
  static const double paddingXxxxxxxxxxxxxxxxxxxxxxxxxxxl = 240.0;
  static const double paddingXxxxxxxxxxxxxxxxxxxxxxxxxxxxl = 248.0;
  static const double paddingXxxxxxxxxxxxxxxxxxxxxxxxxxxxxl = 256.0;
}
